version: "3.8"

services:

  configserver:
    image: vinlyreeks/configserver:1.0.2
    ports:
      - 8889:8889
    networks:
      - iw-network
  discovery:
    image: vinlyreeks/iw-discovery:1.0.1
    ports:
      - 8761:8761
    networks:
      - iw-network
  postgres-compose:
    image: postgres
    ports:
      - "6432:6432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=iw_db


  iw-auth-compose:
    image: vinlyreeks/iw-auth:1.1.4
    ports:
      - "8081:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 120s
    depends_on:
      - discovery
      - configserver
      - postgres-compose
    networks:
      - iw-network
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER: http://configserver:8889
      EUREKA_SERVER: http://discovery:8761/eureka/
      APP_DB_HOST: jdbc:postgresql://postgres-compose:6432:iw_db


networks:
  iw-network:
